        const state = {
            currentScaleX: 1,
            currentScaleY: 1,
            currentSlideIndex: 0,
            slides: [],
            selectedImage: null,
            packageFiles: new Map(),
            requiredAssets: new Set(),
            assetIndex: new Map(),
            assetPathToId: new Map(),
            assetObjectUrls: new Map(),
            imageCounter: 1,
            videoCounter: 1,
            fileCounter: 1,
            documentId: '',
            documentCounter: 1,
            slideCounter: 1,
            elementCounter: 1,
            assetCounter: 1,
            documentModel: null,
            settingsModel: null,
            manifestModel: null,
            isRendering: false,
            clipboardImage: null,
            thumbnailRefreshPending: false,
            lastSaveHandle: null,
            lastPackageFileName: '',
            documentCreatedAt: '',
            legacySource: null,
            documentTitle: 'Presentation',
            isSpacePressed: false,
            activeIframePan: null,
            textEditingElement: null,
            textDefaults: {
                fontFamily: "'Noto Sans KR', 'Apple SD Gothic Neo', 'Malgun Gothic', 'Segoe UI', sans-serif",
                fontSize: 32,
                fontColor: '#111111',
                fontBold: false
            },
            aspectRatio: '16:9',
            displayMode: 'fit',
            currentStageWidth: CONFIG.STAGE_WIDTH_16_9,
            currentStageHeight: CONFIG.STAGE_HEIGHT_16_9
        };
